services:
  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    restart: always

  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guac-postgres
    restart: always
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacuser
      POSTGRES_PASSWORD: GuacStrongPassword123!
    volumes:
      - pgdata:/var/lib/postgresql/data

  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    restart: always
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USER: guacuser
      POSTGRESQL_PASSWORD: GuacStrongPassword123!
    depends_on:
      - guacd
      - postgres

volumes:
  pgdata:
